### PR TITLE
Recursively search for packages, stripping subfolders on each go

### PR DESCRIPTION
**Pull request by jlroettger**
A la the issue I created #1

I haven't tested this (no idea what the build process is for vscode extensions) but it's a pretty simple mod. The extension keeps checking for modules, removing the last subfolder on each iteration until there are no more slashes in the module name.

### CODE REVIEW

**Comment by dkundel** [comment]
Hi Justin!

Thanks for your PR. You can build the project by opening it in VS Code, clicking on Debug and then select "Launch Extension" in the debugger and execute. It will open a new instance of VS Code and attach the debugger as well :)

From what I can see the code should work but it would be great if you could test it :)

**Comment by jlroettger** [comment]
Sweet, got it figured out (mostly). Is the VS Code repo version of this extension different? While testing I could only get the extension to work with `require('whatever')` statements. When I install the extension via the VS Code library, though, it also works fine on `import Whatever from 'whatever'`.

**Comment by dkundel** [comment]
Might be that your TypeScript version is different. Haven't run into that issue yet. The import syntax only works in TypeScript. Maybe it tries to use your global TypeScript if you have one installed.

**Comment by jlroettger** [comment]
Any news/feedback? This PR doesn't touch anything that would cause the strange `require` vs `import` behavior noted above, and aside from that it was working well.

**Comment by dkundel** [comment]
Sorry I kind of got over merging this. I'll try to push a new version this week that should have your changes in.

Cheers,
Dominik

**Pull request merged**
